modalities:
  - name: edaic_audio_mfcc
    input_dim: 39
    model_args:
      latent_dim: 256

  - name: edaic_audio_egemaps
    input_dim: 23
    model_args:
      latent_dim: 256

  - name: edaic_video_cnn_resnet
    input_dim: 2048
    model_args:
      latent_dim: 256

  - name: edaic_video_pose_gaze_aus
    input_dim: 49
    model_args:
      latent_dim: 256
